name: Publicação automática
on:  [workflow_dispatch]
  # nosso script será executado sempre quando houver push e pull request nas branches destacadas abaixo
  #push:
   # branches: [ "main" ]
  #pull_request:
   # branches: [ "main" ]
jobs:
  build:
    # sistema operacional da máquina que o Github irá disponibilizar para rodar o nosso script
    runs-on: ubuntu-latest

    # aqui é iniciado o passo a passo para realizar o processo de publicação
    steps:
      - uses: actions/checkout@v3

      - name: Cria um arquivo temporário para a chave privada 
        run: |
               echo "${{ secrets.KEY }}" > /tmp/private_key
               chmod 600 /tmp/private_key

      - name: Criando a pasta da aplicação e acertando diretório...
        run: |
               ssh -i /tmp/private_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@${{ secrets.HOST }} \
               sudo mkdir -p /var/www/app 

      - name: Ajustar permissões no servidor de Produção
        run: |
          ssh -i /tmp/private_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@${{ secrets.HOST }} "sudo chown -R ubuntu:ubuntu /var/www/app && sudo chmod -R 755 /var/www/app"
                     
      - name: Transferindo os arquivos da aplicação
        run: |
               scp -i /tmp/private_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r ${{ github.workspace }}/* ubuntu@${{ secrets.HOST }}:/var/www/app

      - name: Restaurando a aplicação
        run: |
               ssh -i /tmp/private_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@${{ secrets.HOST }} \
               sudo composer install --working-dir /var/www/app \

      - name: Reiniciando o apache2
        run: |
               ssh -i /tmp/private_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@${{ secrets.HOST }} \
               sudo systemctl restart apache2               

      - name: Limpa o arquivo de chave privada após uso
        run: |
           rm /tmp/private_key
